files:
  ignore:
    - 'node_modules/**/*.*'
    - 'src/sass/lib/**/*.*'
options:
  formatter: stylish
rules:
  force-element-nesting: 0
  hex-length: 0
  indentation:
    - 1
    - size: 4
  nesting-depth:
    - 1
    - max-depth: 4
  property-sort-order:
    - 1
    - order: smacss
